### ISSUE TITLE
"Remove prefix" functionality

### ISSUE THREAD

**Issue by vadakr** [jenkinsci/azure-storage-plugin#191]
If this is the not the place to file an enhancement request, I apologize in advance. 

An example explains this best. Assume that my Jenkins workspace contains the following folder structure -

```
release
|--build
    |--lib
    |--deploy
    |--notices
    |--README.txt
```

I'd like to upload the contents of ${WORKSPACE}/release/build/** into a storage container called ${BUILD_NUMBER}.

My 'Upload' configuration in Jenkins would be as follows -
- List of artifacts to upload: release/build/**
- Container name: ${BUILD_NUMBER}

And what gets created in Azure is -

```
${BUILD_NUMBER}
|--release
    |--build
        |--lib
        |--deploy
        |--notices
        |--README.txt
```

But I'd like it to be -

```
${BUILD_NUMBER}
    |--lib
    |--deploy
    |--notices
    |--README.txt
```

Essentially, I want to strip out the "/release/build" from the path constructed in Azure. This is similar to the functionality offered by the "[Publish over SSH](https://plugins.jenkins.io/publish-over-ssh/)" plugin

**Comment by timja** [comment]
For fine grained control I think you should just use the Azure Storage plugin directly. This plugin is more for seamlessly integrating Jenkins artefacts with cloud storage rather than storing them on the controller file system.

having said that, if you’re using a scripted pipeline this might work if you wrap your ‘archiveArtifacts’ step in a ‘dir’ step to change your directory.

otherwise you need to move your files to the desired upload structure before uploading, or you can just use the azure cli directly where you have complete control

**Comment by sumeetp4** [comment]
Hi @timja , how can I remove prefix from the folders being created on blob?

**Comment by sumeetp4** [comment]
Can't find the option here - 
![image](https://user-images.githubusercontent.com/29970107/133437049-8d12a21b-0a7e-4ec0-b935-30a269d38b7d.png)

**Comment by timja** [comment]
Looks like you have an old version?
According to the code it should be after 'optional list of artifacts'
